### ISSUE TITLE
cache.py not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by ghost** [ruiminshen/yolo2-pytorch#4]
INFO:root:load voc dataset
Traceback (most recent call last):
  File "cache.py", line 70, in <module>
    main()
  File "cache.py", line 50, in main
    module, func = dataset.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by QihuaCheng** [comment]
you need to modify cache.py:
`def main():

         args = make_args()
         config = configparser.ConfigParser()
         utils.load_config(config, args.config)
         #modify
         datasets = config.get('cache', 'datasets').split()

         for cmd in args.modify:
               utils.modify_config(config, cmd)
         with open(os.path.expanduser(os.path.expandvars(args.logging)), 'r') as f:
               logging.config.dictConfig(yaml.load(f))
         cache_dir = utils.get_cache_dir(config)
         os.makedirs(cache_dir, exist_ok=True)
         shutil.copyfile(os.path.expanduser(os.path.expandvars(config.get('cache', 'category'))),os.path.join(cache_dir, 'category'))
         category = utils.get_category(config)
         category_index = dict([(name, i) for i, name in enumerate(category)])
         #previous
         #datasets = config.get('cache', 'datasets').split() `

**Comment by ruiminshen** [comment]
Thank you. I think this problem is solved.
