### ISSUE TITLE
yolo2-pytorch/model_20/model.yolo2.Darknet.ini not found

### ISSUE THREAD

**Issue by QihuaCheng** [ruiminshen/yolo2-pytorch#6]
when i ran quick_start.sh,it show some warning.
`WARNING - training config (pre_model/yolo2-pytorch/model_20/model.yolo2.Darknet.ini) not found`
And i can't found model.yolo2.Darknet.ini in project.

**Comment by ruiminshen** [comment]
It is OK. This file is created by the training program (train.py) which is used to remember the training configuration.
