### ISSUE TITLE
Error when convert darknet model to torch

### ISSUE THREAD

**Issue by xmfbit** [ruiminshen/yolo2-pytorch#8]
When convert the darknet `yolo-voc` weight to torch model, error occurs like this:
```
Traceback (most recent call last):
  File "convert_darknet_torch.py", line 140, in <module>
    main()
  File "convert_darknet_torch.py", line 105, in main
    val = np.array(struct.unpack('%df' % cnt, f.read(cnt * 4)), np.float32)
struct.error: unpack requires a bytes object of length 4096
```
Because I only want to obtain a torch model and evaluate it by myself, I didn't run `quick_start.sh` to do dataset caching. The main steps are as following:

First, I downloaded weight file from website of darknet and put it in $ROOT, which is `$HOME/model/darknet`:
```
wget http://pjreddie.com/media/files/darknet19_448.conv.23
```
And the command I used to convert the model is (just copied from the `quick_start.sh` script):
```
python3 convert_darknet_torch.py ~/model/darknet/darknet19_448.conv.23 -m model/name=model_voc model/dnn=model.yolo2.Darknet -d --copy ~/model/darknet/darknet19_448.conv.23.pth
```
And could you tell me the difference of `darknet19_448.conv.23` and `yolo-voc.weights`? I tried to convert `yolo-voc.weights` and it worked well.

**Comment by ruiminshen** [comment]
Maybe your Darknet model (yolo-voc.weights) is corrupted. Delete this file and download it again.

**Comment by jacktkk** [comment]
@xmfbit 
Did u finish this problem?
I met the same error with u. 
@xmfbit 
sorry, your suggestion didn't work....
